---
- name: Check Apache2 Version and Status
  hosts: all
  become: yes  # Run as sudo
  tasks:
    - name: Check Apache2 version
      ansible.builtin.command: apache2ctl -v
      register: apache_version
      changed_when: false

    - name: Display Apache2 version
      ansible.builtin.debug:
        msg: "Apache2 Version: {{ apache_version.stdout }}"

    - name: Check Apache2 status
      ansible.builtin.service:
        name: apache2
        state: started
      register: apache_status
      check_mode: yes  # Don’t change state, just check

    - name: Display Apache2 status
      ansible.builtin.debug:
        msg: "Apache2 is {{ 'running' if apache_status.state == 'started' else 'not running' }}"
