---
- name: Test Apache Web Server
  hosts: "{{ target_hosts | default('all') }}"
  become: yes
  gather_facts: yes

  vars:
    apache_package: "apache2"  # Change to "httpd" for RHEL/CentOS
    apache_service: "apache2"  # Change to "httpd" for RHEL/CentOS
    apache_doc_root: "/var/www/html"
  
  tasks:
    - name: Install Apache
      package:
        name: "{{ apache_package }}"
        state: present

    - name: Ensure Apache is running
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: yes

    - name: Create test page
      copy:
        content: "AWX Apache Test Successful"
        dest: "{{ apache_doc_root }}/awx-test.html"
        mode: '0644'

    - name: Test HTTP response
      uri:
        url: "http://{{ inventory_hostname }}/awx-test.html"
        return_content: yes
      register: test_response

    - name: Verify test page content
      assert:
        that: 
          - "test_response.status == 200"
          - "'AWX Apache Test Successful' in test_response.content"

    - name: Clean up test page
      file:
        path: "{{ apache_doc_root }}/awx-test.html"
        state: absent

