---
- name: Apply Security Patches to Ubuntu 24.04 and Apache2
  hosts: all
  connection: ssh
  become: yes
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      register: cache_update

    - name: Check for reboot requirement
      ansible.builtin.command: /usr/bin/needs-restarting -r
      register: reboot_needed
      changed_when: false
      failed_when: false

    - name: Display patching results
      ansible.builtin.debug:
        msg:
          - "Cache updated: {{ cache_update.changed | ternary('Yes', 'No') }}"
          - "Packages updated: {{ apt_upgrade.changed | ternary('Yes', 'No') }}"
          - "Apache2 restarted: {{ apache_restart.changed | ternary('Yes', 'No') }}"
          - "Reboot required: {{ reboot_needed.rc == 1 | ternary('Yes', 'No') }}"
