---
- name: Apply Security Patches to Ubuntu 24.04 and Apache2
  hosts: localhost
  connection: local  # Run on the AWX VM itself
  become: yes        # Escalate to sudo
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Refresh cache if older than 1 hour

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: no  # Already updated above
      register: apt_upgrade

    - name: Check if Apache2 needs restart
      ansible.builtin.service:
        name: apache2
        state: restarted
      when: apt_upgrade.changed and 'apache2' in apt_upgrade.stdout
      register: apache_restart

    - name: Display patching results
      ansible.builtin.debug:
        msg:
          - "Packages updated: {{ apt_upgrade.changed | ternary('Yes', 'No') }}"
          - "Apache2 restarted: {{ apache_restart.changed | ternary('Yes', 'No') }}"
